name: simple_app # Replace with your actual app name if different
description: A Flutter application demonstrating profile view, editing, and theme switching.
publish_to: "none" # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Adjust SDK constraints as needed for your Flutter version

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15 # Or use a newer compatible version

  # Add other dependencies here if needed
  # e.g., cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Optional: for code analysis

flutter:
  uses-material-design: true
  assets:
    - assets/ # Add assets


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
